### ISSUE TITLE
Team Todo(0131 ~ 0207)

### ISSUE THREAD

**Issue by ji-water** [Smilegate-WWW/wow-welcome-webtoon#16]
### 모장현
- [ ] 베스트댓글 x

- [ ] 댓글 올리기 x

### 백지수

- [x] 회원가입할때 암호화해서 DB넣고

- [x]  jwt 적용하기!!!!!!!!!!!!!!!! 

- [x] refresh jwt, redis 찾아보기 

<details>
    <summary> 일간 개발 성과 </summary>

[01/31] DB entity 수정 및 post 전송된 데이터 + datetime삽입 확인
[02/01] sha256 + salt 적용 
[02/02] bcrypt 적용 및 controller, service class 분리, 로그인 api 수정 중 *dcrypt아님..bcrypt.. 
[02/03] jwt 생성 및 인증 코드 추가
[02/04] 
(해야할것) refresh jwt, redis, secret key 생성 찾아보기 api,url 다듬기 + error code 추가하기 
</details>

### 유효민

- [x]  화면 전체 짜기!!

### 정연우

- [x] 웹툰 DB 업로드
