### ISSUE TITLE
Team Todo(0207 ~ 0214)

### ISSUE THREAD

**Issue by ji-water** [Smilegate-WWW/wow-welcome-webtoon#19]
### 모장현
- [ ] api 문서 작성
- [x] 댓글 기본 기능 완성(네이버 댓글에 수정은 없어서 일단 빼고 기본 crd 기능만 처리)
- [x] 댓글 좋아요 / 싫어요
- [x] 댓글 페이징
- [x] 베스트 댓글

### 백지수
- [x] 인증서버 
- [x] api 문서 작성, 에러코드 문서 작성
- [ ] 프론트 토큰 추가
- [x] 멀티 프로젝트
- [x] 프론트-백엔드 연결 찾아보기 
![image](https://user-images.githubusercontent.com/47727109/74306642-6ef9dc80-4da6-11ea-969e-ea5490657bec.png)

<details>
<summary> 참고 </summary>

[rest api와 웹서버 호출 관계?]
https://okky.kr/article/542755
[RSSR react serverside rendering]
https://www.popit.kr/react-%EC%84%9C%EB%B2%84%EC%82%AC%EC%9D%B4%EB%93%9C-%EB%A0%8C%EB%8D%94%EB%A7%81/
[RSSR]
https://subicura.com/2016/06/20/server-side-rendering-with-react.html
[읽어볼것 >> ]
https://synyx.de/blog/springboot-reactjs-server-side-rendering/ 
[gradle 멀티프로젝트] 모듈간 의존성 추가해서 A모듈에서 B모듈 서비스 호출하기 가능
https://www.hanumoka.net/2019/10/04/springBoot-20191004-springboot-gradle-multimodule/
</details>

### 유효민
- [ ] 프론트 데이터 형태 변경
- [ ] 로그인 필요하면 넘겨주기

### 정연우
- [ ] api 문서 작성
- [x] 웹툰 회차 등록
- [ ] 웹툰 정보 수정 
- [x] 회차 리스트 보여주기

* 웹툰 리스트 5*4 개
* 회차 리스트 7개
* 댓글 리스트 15개

**Comment by ji-water** [comment]
request content 관련 읽어볼만한 것 같아서 가져왔어요
https://gist.github.com/jays1204/703297eb0da1facdc454
