### ISSUE TITLE
Team Todo(0214 ~ 0221)

### ISSUE THREAD

**Issue by ji-water** [Smilegate-WWW/wow-welcome-webtoon#26]
### 모장현
- [ ] 별점 시스템
- [ ] api 문서작성

### 백지수
- [x] nginx (이번주)
- [ ] 프론트 토큰 추가
- [x] core project 로 entity랑 repository 설정 옮기기
- [x] access token parser core로 옮기기!~!~!~~!~!~!~
- [ ] db 서버시간 설정 찾아보기
- [x] eclipse 빌드 인코딩 찾아보기 . . . . .. . . . 하하하하하하하하ㅏ

### 유효민
- [x] 회원 정보 수정
- [x] 작품 정보 수정
- [ ] backend 연결 하기 ( 화이팅... . . . .... . . .. )

### 정연우
- [x] 웹툰 이미지 출력
- [x] 이미지 url 만들기
- [x] 토큰 읽어오기
- [x] core project로 entity랑 repository 설정옮기기
- [x] 예외처리
- [x] 회차정보 수정
- [x] 회차 순서 ::: 웹툰, 회차 수정 시에 이미지 파일 수정 여부 확인 ?...
- [x] API 문서
