### ISSUE TITLE
Team Todo (20.02.28~20.03.06)

### ISSUE THREAD

**Issue by ji-water** [Smilegate-WWW/wow-welcome-webtoon#35]
* 모장현

* 백지수
- [ ] 추가된 api 프록시 서버
- [ ] 저 테스트 코드 작성해볼수있을거같아요

* 유효민

* 정연우
- [ ] 머시기 인덱스 추가
