### ISSUE TITLE
Team Todo(0117 ~ 0131)

### ISSUE THREAD

**Issue by momojh94** [Smilegate-WWW/wow-welcome-webtoon#6]
### 모장현
 - [x] 환경 설정 - 버전 정하기, 환경 구축  #7 
 - [ ] 댓글 기능
 - [ ] 베스트 댓글 기능
 - [ ] 별점
 - [x] 기능별 DB 데이터 정리

-----
### 백지수
- [x] 환경 설정 - 버전 정하기, 환경 구축  #7 
- [ ] 로그인/회원가입 인증 처리 적용
- [x] 로그인 DB 데이터 정리 

-----
### 정연우
- [ ] 환경 설정 - 버전 정하기, 환경 구축  #7 
- [ ] 이미지 업로드 기능 구현
- [x] 이미지 DB 데이터 정리

-----
### 유효민
- [ ] 프론트엔드 공부하기
